In [ ]:
!pip install -q openprompt==0.1.1 \
'torch>=1.9.0' \
'transformers>=4.10.0' \
sentencepiece==0.1.96 \
'scikit-learn>=0.24.2' \
'tqdm>=4.62.2' \
tensorboardX \
nltk \
yacs \
dill \
datasets \
rouge==1.0.0 \
scipy==1.4.1 \
fugashi \
ipadic \
unidic-lite

In [1]:
import xml.etree.ElementTree as ET
tree = ET.parse('./smokers_surrogate_train_all_version2.xml')
root = tree.getroot()

In [2]:
root.attrib
root.tag
counter=0
for child in root:
    if counter == 10:
        break
    print(child.tag, child.attrib)
    counter +=1
    

RECORD {'ID': '641'}
RECORD {'ID': '643'}
RECORD {'ID': '681'}
RECORD {'ID': '704'}
RECORD {'ID': '757'}
RECORD {'ID': '786'}
RECORD {'ID': '872'}
RECORD {'ID': '874'}
RECORD {'ID': '535'}
RECORD {'ID': '540'}


In [3]:
[elem.tag for elem in root.iter()]

counter=0
for elem in root.iter():
    if counter==10:
        break
    print(elem.tag)
    counter+=1

ROOT
RECORD
SMOKING
TEXT
RECORD
SMOKING
TEXT
RECORD
SMOKING
TEXT


In [4]:
counter=0
for smoking in root.iter('SMOKING'):
    if counter==10:
        break
    print(smoking.attrib.get('STATUS'))
    counter +=1
    
# for movie in root.iter('SMOKING'):
#     print(movie.attrib)

CURRENT SMOKER
CURRENT SMOKER
CURRENT SMOKER
CURRENT SMOKER
CURRENT SMOKER
CURRENT SMOKER
CURRENT SMOKER
CURRENT SMOKER
CURRENT SMOKER
CURRENT SMOKER


In [5]:
# for text in root.iter('TEXT'):
#     print(text.text)
    
counter=0
for text in root.iter('TEXT'):
    if counter==1:
        break
    print(text.text)
    counter +=1    


977146916
HLGMC
2878891
022690
01/27/1997 12:00:00 AM
CARCINOMA OF THE COLON .
Unsigned
DIS
Report Status :
Unsigned
Please do not go above this box important format codes are contained .
DISCHARGE SUMMARY
ARF32 FA
DISCHARGE SUMMARY NAME :
GIRRESNET , DIEDREO A
UNIT NUMBER :
075-71-01
ADMISSION DATE :
01/27/1997
DISCHARGE DATE :
01/31/1997
PRINCIPAL DIAGNOSIS :
Carcinoma of the colon .
ASSOCIATED DIAGNOSIS :
Urinary tract infection , and cirrhosis of the liver .
HISTORY OF PRESENT ILLNESS :
The patient is an 80-year-old male , who had a history of colon cancer in the past , resected approximately ten years prior to admission , history of heavy alcohol use , who presented with a two week history of poor PO intake , weight loss , and was noted to have acute on chronic Hepatitis by chemistries and question of pyelonephritis .
He lived alone but was driven to the hospital by his son because of reported worsening and general care and deconditioning .
Emergency Department course ; he was ev

In [6]:
counter=0
for text in root.findall("./SMOKING/[@STATUS='CURRENT SMOKER']"):
    if counter==10:
        break
    print(text.attrib)
    print(counter)
    counter +=1    

In [7]:
# doc=xee.fromstring('./smokers_surrogate_train_all_version2.xml')

for tag in root.findall('SMOKING'):
    if tag.attrib['STATUS']!='CURRENT SMOKER':
#         root.remove(tag)
        print(tag)
        
# print(ET.tostring(root))

In [8]:
# node=root
# if node.tag == "SMOKING":
#         status = node.attrib.get("STATUS")
#         print(status)
#         if status is not None:
#             print(node.attrib.get("TEXT"))
import xml.etree.ElementTree as ET
tree = ET.parse('./smokers_surrogate_train_all_version2.xml')
root = tree.getroot()

text_list=[]
counter =0             
for record in root.iter('RECORD'):
    if counter == 2:
        break
    print(record.attrib.get('ID'))
    smoking = record.find('SMOKING')
    print(smoking.attrib.get('STATUS'))
    if smoking.attrib.get('STATUS')=="CURRENT SMOKER":
        text=record.find('TEXT')
        text_list.append(text)
        print(counter)
    counter +=1

641
CURRENT SMOKER
0
643
CURRENT SMOKER
1


In [16]:
import xml.etree.ElementTree as ET
tree = ET.parse('./smokers_surrogate_train_all_version2.xml')
root = tree.getroot()

text_list=[]
label_list=[]
counter =0             
for record in root.iter('RECORD'):
#     if counter:
#         break
#     print(record.attrib.get('ID'))
    smoking = record.find('SMOKING')
    label_list.append(smoking.attrib.get('STATUS'))
#     print(smoking.attrib.get('STATUS'))
    text=record.find('TEXT')
    text_list.append(text)
#     print(text_list.__len__())
#     print(counter)
    counter +=1

In [18]:
print(text_list.__len__())
print(label_list.__len__())

398
398


In [19]:
label_list

['CURRENT SMOKER',
 'CURRENT SMOKER',
 'CURRENT SMOKER',
 'CURRENT SMOKER',
 'CURRENT SMOKER',
 'CURRENT SMOKER',
 'CURRENT SMOKER',
 'CURRENT SMOKER',
 'CURRENT SMOKER',
 'CURRENT SMOKER',
 'CURRENT SMOKER',
 'CURRENT SMOKER',
 'CURRENT SMOKER',
 'CURRENT SMOKER',
 'CURRENT SMOKER',
 'CURRENT SMOKER',
 'CURRENT SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 'NON-SMOKER',
 '

# Datset

In [1]:
import torch
from torch.utils.data.dataset import Dataset
import pandas as pd
from torch.utils.data import Dataset, DataLoader
 
use_cuda = torch.cuda.is_available()
device = torch.device("cuda:0" if use_cuda else "cpu")
print(device)
 
 
class CustomTextDataset(Dataset):
    def __init__(self, text, labels):
        self.labels = labels
        self.text = text
        
    def __len__(self):
            return len(self.labels)
        
    def __getitem__(self, idx):
            label = self.labels[idx]
            text = self.text[idx]
            sample = {"Text": text, "Class": label}
            return sample

cuda:0


In [2]:
import pandas as pd

text = ['Happy', 'Amazing', 'Sad', 'Unhapy', 'Glum']
labels = ['Positive', 'Positive', 'Negative', 'Negative', 'Negative']

text_labels_df = pd.DataFrame({'Text': text, 'Labels': labels})

TD = CustomTextDataset(text_labels_df['Text'],
                       text_labels_df['Labels'])

In [3]:
# Display text and label.
print('\nFirst iteration of data set: ', next(iter(TD)), '\n')
# Print how many items are in the data set
print('Length of data set: ', len(TD), '\n')
# Print entire data set
print('Entire data set: ', list(DataLoader(TD)), '\n')


First iteration of data set:  {'Text': 'Happy', 'Class': 'Positive'} 

Length of data set:  5 

Entire data set:  [{'Text': ['Happy'], 'Class': ['Positive']}, {'Text': ['Amazing'], 'Class': ['Positive']}, {'Text': ['Sad'], 'Class': ['Negative']}, {'Text': ['Unhapy'], 'Class': ['Negative']}, {'Text': ['Glum'], 'Class': ['Negative']}] 



# BERT
OpenPrompt

In [4]:
import openprompt.plms as plms
from openprompt.plms.mlm import MLMTokenizerWrapper
from transformers import BertConfig, BertForMaskedLM, BertTokenizer

In [5]:
plms._MODEL_CLASSES['bert'] = plms.ModelClass(**{
    'config': BertConfig,
    'tokenizer': BertTokenizer,
    'model':BertForMaskedLM,
    'wrapper': MLMTokenizerWrapper,
})

In [6]:
plms._MODEL_CLASSES

{'bert': ModelClass(config=<class 'transformers.models.bert.configuration_bert.BertConfig'>, tokenizer=<class 'transformers.models.bert.tokenization_bert.BertTokenizer'>, model=<class 'transformers.models.bert.modeling_bert.BertForMaskedLM'>, wrapper=<class 'openprompt.plms.mlm.MLMTokenizerWrapper'>),
 'roberta': ModelClass(config=<class 'transformers.models.roberta.configuration_roberta.RobertaConfig'>, tokenizer=<class 'transformers.models.roberta.tokenization_roberta.RobertaTokenizer'>, model=<class 'transformers.models.roberta.modeling_roberta.RobertaForMaskedLM'>, wrapper=<class 'openprompt.plms.mlm.MLMTokenizerWrapper'>),
 'albert': ModelClass(config=<class 'transformers.models.albert.configuration_albert.AlbertConfig'>, tokenizer=<class 'transformers.models.albert.tokenization_albert.AlbertTokenizer'>, model=<class 'transformers.models.albert.modeling_albert.AlbertForMaskedLM'>, wrapper=<class 'openprompt.plms.mlm.MLMTokenizerWrapper'>),
 'gpt': ModelClass(config=<class 'transfo

# Step 1: Define a task
|

In [20]:
from openprompt.data_utils import InputExample
classes = [ 
    "Smoking",
    "not Smoking"
]

dataset = [ 
      InputExample(
        guid = 0,
        text_a = """ smoking causes cancer
        """, #smoking
    ),
    InputExample(
        guid = 1,
        text_a = """"This person doesnt smoke""", #obsese
    ),
#     InputExample(
#         guid = 2,
#         text_a = "When your brain is damaged, it can affect many different things, including your memory, your sensation, and even your personality. Brain disorders include any conditions or disabilities that affect your brain.", #brain
#     ),
#     InputExample(
#         guid = 3,
#         text_a = "Symptoms may appear 2-14 days after exposure to the virus", #virus
#     ),
        InputExample(
        guid = 4,
        text_a = """The patient is healthy and is having a balanced diet.""", #healthy
    ),
]



# Step 2: Define a Pre-trained Language Models (PLMs)

In [21]:
from transformers import AutoTokenizer, AutoModel
from openprompt.plms import load_plm
# plm, tokenizer, model_config, WrapperClass = load_plm("bert", "bert-base-uncased")
plm, tokenizer, model_config, WrapperClass = load_plm("bert", "emilyalsentzer/Bio_ClinicalBERT")
# plm, tokenizer, model_config, WrapperClass = load_plm("bert", "mrm8488/bioclinicalBERT-finetuned-covid-papers")

Some weights of the model checkpoint at emilyalsentzer/Bio_ClinicalBERT were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [22]:
tokenizer.tokenize("I think this drug is not a solution")

['i', 'think', 'this', 'drug', 'is', 'not', 'a', 'solution']

# Step 3: Define a Template.


In [23]:
from openprompt.prompts import ManualTemplate
from openprompt.prompts import PtuningTemplate
# template_text = '{"placeholder":"text_a"}: This effects {"mask"}'
template_text= 'A {"mask"} disorder :  {"placeholder": "text_a"}'

# promptTemplate = ManualTemplate(
#     text = template_text,
#     tokenizer = tokenizer,
# )

promptTemplate = PtuningTemplate(model = plm, 
                                 tokenizer = tokenizer, 
                                 text = template_text, 
                                 prompt_encoder_type = 'mlm'
)

# Step 4: Define a Verbalizer


In [24]:
from openprompt.prompts import ManualVerbalizer
promptVerbalizer = ManualVerbalizer(
    classes = classes,
    label_words = {
        "Smoking": ["smoking", "tobacco", "cigarette"],
        "not Smoking": ["healthy"] #"healthy", 
    },
    tokenizer = tokenizer,
)

# Step 5: Combine them into a PromptModel
Given the task, now we have a PLM, a Template and a Verbalizer,  combine them into a PromptModel. 

In [25]:
from openprompt import PromptForClassification
promptModel = PromptForClassification(
    template = promptTemplate,
    plm = plm,
    verbalizer = promptVerbalizer
)

# Step 6: Define a DataLoader
A PromptDataLoader is basically a prompt version of pytorch Dataloader, which also includes a Tokenizer, a Template and a TokenizerWrapper.

In [26]:
from openprompt import PromptDataLoader
data_loader = PromptDataLoader(
    dataset = dataset,
    tokenizer = tokenizer, 
    template = promptTemplate, 
    tokenizer_wrapper_class=WrapperClass,
    max_seq_length=256, decoder_max_length=3, 
    batch_size=1,shuffle=False, teacher_forcing=False, predict_eos_token=False,
    truncate_method="head"
)


tokenizing: 3it [00:00, 928.42it/s]


# Step 7: Train and inference
Done! We can conduct training and inference the same as other processes in Pytorch.

In [27]:
# making zero-shot inference using pretrained MLM with prompt
import torch
promptModel.eval()
with torch.no_grad():
    for batch in data_loader:
        logits = promptModel(batch)
        print(logits)
        preds = torch.argmax(logits, dim = -1)
        
        print(classes[preds])
# predictions would be 1, 0 for classes 'positive', 'negative'


tensor([[-3.0085, -6.5984]])
Smoking
tensor([[-2.7888, -8.5340]])
Smoking
tensor([[-6.2428, -0.0253]])
not Smoking
